Added support for sed's `-E` alias of `-r`
RedHatInsights/insights-core pull request #1323
Opened 2018-08-06 08:22 UTC by sourabhtk37

Closes #1277 
Signed-off-by: T K Sourab <sourabhtk37@gmail.com>

2018-09-13 14:52 UTC, kylape commented
ok to test

2018-09-13 14:58 UTC, YakovLittle commented
test this please

2018-09-13 15:01 UTC, YakovLittle commented
test this please

2018-09-13 15:05 UTC, eduardocerqueira commented
retest this please

2018-09-13 15:16 UTC, esakaiev commented
test this please

2019-01-29 19:39 UTC, kylape commented
test this please

2019-01-30 10:21 UTC, sourabhtk37 commented
@kylape Anything needs to be done?

2021-05-04 10:52 UTC, psachin commented
Hey @sourabhtk37 Can you confirm if this PR is still valid?

2021-05-04 13:12 UTC, sourabhtk37 commented
@psachin Yes, it's valid.

2021-05-10 13:56 UTC, sourabhtk37 commented
@psachin I have resolved but please give me some time to complete as I see there is few more places that needs support for the same.

2021-05-13 17:28 UTC, sourabhtk37 commented
@psachin Updated the changes.

2022-01-05 04:48 UTC, psachin commented
@gravitypriest I think this change is valid. If you are OK with this change, can we merge it ?

2022-01-05 08:46 UTC, psachin approved these changes

2023-09-26 13:29 UTC, Glutexo requested changes

2023-10-01 10:36 UTC, Glutexo commented on insights/client/insights_spec.py
> +        sedcmd = Popen(['sed', '-Ef', self.real_path], stdout=PIPE)
The introduced bug can be even seen in the output:

```
sed: file /etc/redhat-access-insights/machine-id line 1: extra characters after command
sed: file /etc/machine-id line 1: extra characters after command
sed: file /usr/lib/udev/rules.d/40-redhat.rules line 4: unknown command: `S'
sed: file /proc/1/cgroup line 1: : doesn't want any addresses
sed: file /etc/insights-client/insights-client.conf line 1: unknown command: `['
```

2023-10-01 10:57 UTC, Glutexo commented
I reverted the changes in _insights_spec.py_ that introduced a bug, fixing that. I verified the change in _data_collector.py_ and confirm it works fine even on RHEL 6.

2023-10-01 11:15 UTC, Glutexo commented
@psachin May I ask you (or anyone else) for a new review?

### Steps to verify

1. Run the Insights collection.

   ```sh
   # BYPASS_GPG=True EGG=insights-core insights-client --no-gpg --offline
   Starting to collect Insights data for localhost.localdomain
   Archive saved at /var/tmp/OLvKyC/insights-localhost.localdomain-20230926145152.tar.gz
   ```

2. Inspect a file containing “password” in the archive

   ```sh
   # tar -xOf /var/tmp/OLvKyC/insights-localhost.localdomain-20230926145152.tar.gz ./insights-localhost.localdomain-20230926145152/etc/pam.d/password-auth
   …
   password    ********     ********
   …
   ```

   If the regular expression works correcly, a line containing “password” replaces all following words with “********”. A non-extended regular expression would make the replacement to not work, printing errors like
   
   > sed: file /etc/insights-client/.exp.sed line 2: invalid reference \2 on `s' command's RHS

3. Check that the output does not contain sed errors like
   
   > sed: file /etc/redhat-access-insights/machine-id line 1: extra characters after command.
   
   Although the collection would halt in case of a malfunctioning sed command in  _insights_spec.py_.

2023-10-02 09:25 UTC, Glutexo approved these changes

2023-10-09 18:41 UTC, ryan-blakley commented
I just wanted to mention PR #3900 as it removes the sed command call in the data_collection.py file.

2023-10-18 21:06 UTC, Glutexo commented
There is another pull request #3900 that removes usage of _sed_ entirely. Because of that, any changes to the sed command are unnecessary. Closing then. Thanks, @ryan-blakley!

2023-10-18 21:06 UTC, closed without merging