Enhance that there are two or more values of the same key in a dictio…
RedHatInsights/insights-core pull request #2717
Opened 2020-08-19 07:51 UTC by shlao

Updated
```
insights/parsers/__init__.py
```

Here are the codes of parser SystemctlShowServiceAll:
```
 19 class SystemctlShowServiceAll(CommandParser, dict):
 79     def parse_content(self, content): 
 90         for s, e in idx_list:
 91             data = split_kv_pairs(content[s:e], use_partition=False)
 92             name = data.get('Names', data.get('Id'))
 93             if not name:
 94                 raise ParseException('"Names" or "Id" not found!')
 95             self[name] = dict((k, v) for k, v in data.items() if v)
```

Here are the testing data (on RHEL8):
```
# systemctl show sshd.service  > /tmp/sshd.txt
# cat /tmp/sshd.txt | grep Env
EnvironmentFiles=/etc/crypto-policies/back-ends/opensshserver.config (ignore_errors=yes)
EnvironmentFiles=/etc/sysconfig/sshd (ignore_errors=yes)
the function split_kv_pairs will overwrite the dictionary value of the same key EnvironmentFiles and only save the last value.
```

Signed-off-by: shlao <shlao@redhat.com>

2020-08-19 07:53 UTC, shlao commented
If the key has existed then it is well to combine two dictionary values.
for example, what we get from expression service_conf['sshd.service']['EnvironmentFiles'] is:
`['/etc/crypto-policies/back-ends/opensshserver.config', '/etc/sysconfig/sshd']`

2020-08-20 02:23 UTC, shlao commented
@xiangce @bfahr Will you help me to review this?

2020-08-21 04:40 UTC, xiangce commented on insights/parsers/__init__.py
> +def set_dict_value(this_dict, key, value):
I think this function makes things more complex.

2020-08-21 04:53 UTC, xiangce commented on insights/parsers/__init__.py
> +            set_dict_value(kv_pairs, k.strip(), v.strip())
How about changing it like:
```diff
+        k, v = [None, None]
         if not use_partition:
             if split_on in line:
-                k, v = line.split(split_on, 1)
-                set_dict_value(kv_pairs, k.strip(), v.strip())
+                k, v = [i.strip() for i in line.split(split_on, 1)]
         else:
-            k, _, v = line.partition(split_on)
-            set_dict_value(kv_pairs, k.strip(), v.strip())
+            k, _, v = [i.strip() for i in line.partition(split_on)]
+        if k is not None:
+            if k not in kv_pairs:
+                kv_pairs[k] = v
+            else:
+                _v = kv_pairs[k]
+                _v = [_v] if not isinstance(_v, list) else _v
+                _v.append(v)
```

2020-08-21 05:47 UTC, shlao commented on insights/parsers/__init__.py
> +            set_dict_value(kv_pairs, k.strip(), v.strip())
Let me try it in my host.

2020-08-26 09:35 UTC, xiangce reviewed
@shlao  Would you please update the `Examples` for this change as well?

2020-08-27 06:01 UTC, xiangce approved these changes

2020-08-27 06:02 UTC, xiangce commented
@bfahr - This change looks good to me, please help double confirm.

2020-09-04 03:31 UTC, shlao commented
@bfahr Will you help me to review this PR, thanks!

2020-09-09 22:22 UTC, csams commented
The proposed impl would require users to test every value to see whether it's a list or not. I prefer to keep the existing impl and handle the duplicate key use case separately, either in a different function or with a keyword argument to the current one. e.g. if `allow_duplicates` is true, _all_ values should be lists for consistency. Otherwise, go with the current behavior where the last duplicate key wins.

2020-09-10 00:55 UTC, xiangce commented
> The proposed impl would require users to test every value to see whether it's a list or not. I prefer to keep the existing impl and handle the duplicate key use case separately, either in a different function or with a keyword argument to the current one. e.g. if `allow_duplicates` is true, _all_ values should be lists for consistency. Otherwise, go with the current behavior where the last duplicate key wins.

I like the `allow_duplicates` idea. Thank you Chris. @shlao how do you think? Would you please update per Chris's proposal?

2020-09-10 01:12 UTC, shlao commented
@csams  Good idea. @xiangce  Will add a parameter `allow_duplicates` to make the parser backward-compatible.

2020-09-10 10:58 UTC, shlao commented
@csams if all values should be lists for consistency:
```
        >>> split_kv_pairs(lines, allow_duplicates=True)
        {'keyword2': ['value2a=True, value2b=100M'], 'keyword1': ['value1', 'value2']}
```

The the we need to change a lot in parser SystemctlShowServiceAll:
```
 91             data = split_kv_pairs(content[s:e], use_partition=False, allow_duplicates=True)
 92             name = data.get('Names', data.get('Id'))
 95             self[name] = dict((k, v) for k, v in data.items() if v)
```
Line 95 will hit this error
TypeError: unhashable type: 'list'

2020-09-10 11:15 UTC, shlao commented
@csams So I change it to store values in a list when there are two or more lines that have the same key
```
                     _v = kv_pairs[k]
                    _v = [_v] if not isinstance(_v, list) else _v
```

2020-09-11 05:23 UTC, xiangce commented
> @csams if all values should be lists for consistency:
> 
> ```
>         >>> split_kv_pairs(lines, allow_duplicates=True)
>         {'keyword2': ['value2a=True, value2b=100M'], 'keyword1': ['value1', 'value2']}
> ```
> 
> The the we need to change a lot in parser SystemctlShowServiceAll:
> 
> ```
>  91             data = split_kv_pairs(content[s:e], use_partition=False, allow_duplicates=True)
>  92             name = data.get('Names', data.get('Id'))
>  95             self[name] = dict((k, v) for k, v in data.items() if v)
> ```
> 
> Line 95 will hit this error
> TypeError: unhashable type: 'list'

@shlao - This is because the `name` is also wrapped into a list, it can be resolved by:
```python
            # There must be one and only one "name" as the key
            if not name or len(name) > 1:
                raise ParseException('"Names" or "Id" not found!')
            name = name[0]
            self[name] = dict((k, v) for k, v in data.items() if v)
```

As Chris mentioned, if only store the keys with multiple values into a list, it would require users to test every value to see whether it's a list or not. I don't think this is what we want.

2020-09-11 07:54 UTC, shlao commented
@xiangce  @csams  You can see what are changes in latest pr.
Beside that, we need to change the rules using the Parsers which invoke function split_kv_pairs:
```
postgresql_on_external_disk
httpd_fails_to_start_during_boot
sssd_network_user_auth_issue
```

2020-09-11 08:06 UTC, xiangce commented
@shlao - Yeap, that's the impact of this update (applying the "allow_duplicates=Ture" to this parser). It's reasonable for me to make this parser more flexible to support these `duplicated keys` (like a bugfix). And we'd better use this parser in this way (I think we should update the existing rules). @bfahr - How do you think?

2020-09-16 19:51 UTC, bfahr commented on insights/parsers/systemctl_show.py
> +        DummyKey1 = Value2
Is this valid for there to be two keys with the same name for a particular services in the output of this command?

2020-09-16 20:08 UTC, bfahr requested changes

2020-09-16 20:08 UTC, bfahr commented on insights/parsers/systemctl_show.py
> +                "DummyKey1"        : ["Value1", "Value2"]
Based on my comment above, these examples should all be lists.

2020-09-16 20:08 UTC, bfahr commented on insights/parsers/systemctl_show.py
> +        ['NetworkManager.service']
Same comment as above, I believe all values will be a `list` type.  Will this command actually return duplicates that require a list?

2024-04-27 08:33 UTC, shlao commented
I close this one because there is no requirements now.

2024-04-27 08:33 UTC, closed without merging