add --module option to run modules from cli
RedHatInsights/insights-core pull request #2792
Opened 2020-10-20 20:07 UTC by gravitypriest

Signed-off-by: Jeremy Crafts <jcrafts@redhat.com>

2020-10-21 14:25 UTC, subpop requested changes

2020-10-21 14:25 UTC, subpop commented on insights/client/config.py
> +    'module': {
Can we make this option hidden from the `--help` output by default, since it's not really meant for public consumption?

2020-10-26 17:08 UTC, subpop approved these changes

2020-11-05 12:47 UTC, patchkez commented
test this please

2020-11-10 19:31 UTC, gravitypriest commented
Merging because only test failures are test-unregister, unrelated to change set.

2020-11-10 19:31 UTC, merged