[spec] Add spec for collecting ansible_host
RedHatInsights/insights-core pull request #3019
Opened 2021-04-13 13:41 UTC by SteveHNH

The client will begin collecting ansible_host and putting it into the
root of the archive. This spec will let us dig it out of puptoo for
system_profile

RHCLOUD-13536

Signed-off-by: Stephen Adams <tsadams@gmail.com>

2021-04-13 20:03 UTC, bfahr commented
@SteveHNH I submitted #3008 for @gravitypriest but I'll close it and use this one instead.  It also needs to go through spec approval.

2021-04-13 20:06 UTC, bfahr approved these changes
Approved pending spec approval

2021-04-13 20:08 UTC, bfahr requested changes

2021-04-13 20:08 UTC, bfahr commented on insights/specs/insights_archive.py
> +    ansible_host = simple_file("ansible_host")
This change is not required, it will be covered by the `Core3Specs`.

2021-04-13 20:32 UTC, SteveHNH commented
@bfahr all fixed up

2021-04-14 22:09 UTC, bfahr requested changes

2021-04-14 22:09 UTC, bfahr commented on insights/specs/core3_archive.py
> -    display_name = simple_file("display_name")
@SteveHNH leave this here, and add `ansible_host` here as well to support core processing of core-collection archives.

2021-04-14 22:09 UTC, bfahr commented on insights/specs/default.py
> +    ansible_host = simple_file("ansible_host")
Remove this spec and add it to `insights_archive.py` to support reading non-core-collection archives.

2021-04-14 22:09 UTC, bfahr commented on insights/specs/default.py
> +    display_name = simple_file("display_name")
Remove this spec, its already in `insights_archive.py`.

2021-04-15 15:50 UTC, bfahr approved these changes

2021-04-15 15:51 UTC, merged