New specs and parsers for scsi_mod, lpfc driver and qla2xxx driver ma…
RedHatInsights/insights-core pull request #3221
Opened 2021-09-15 07:30 UTC by qinpingli

…x luns

### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

These specs and parsers are used to detect linux reports lun<nnn> has a LUN larger than allowed by the host adapter issue.  Detailed info is in the CEECBA-5708.

2021-09-15 16:29 UTC, bfahr requested changes

2021-09-15 16:29 UTC, bfahr commented on insights/parsers/sys_module.py
> +    Examples::
`Examples:` should only have 1 colon.  See the [recommended style guide](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html) for more information.

2021-09-15 16:29 UTC, bfahr commented on insights/parsers/sys_module.py
> +    Examples::
Same comment as above.

2021-09-15 16:29 UTC, bfahr commented on insights/parsers/sys_module.py
> +    Examples::
Same comment as above.

2021-09-15 16:29 UTC, bfahr commented on insights/parsers/sys_module.py
> +        val(str): Raw data of the content.
@qinpingli the type for this attribute should be `int`.

2021-09-16 01:28 UTC, qinpingli commented
@bfahr Thanks for the review! Created a commit to fix them, please help take a look again.

2021-09-20 20:05 UTC, vdymna approved these changes
This looks good to me.

2021-09-20 20:07 UTC, merged