feat: New parser for systemd_perms
RedHatInsights/insights-core pull request #3339
Opened 2022-02-16 17:02 UTC by TZ3070

Signed-off-by: Xinting Li <xintli@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

2022-02-21 07:48 UTC, TZ3070 commented
@xiangce Please have a review.

2022-02-21 07:52 UTC, xiangce requested changes
@TZ3070 - These two parsers are in fact `Ls` like parsers, would you please rename them with a prefix `Ls` like others, e.g. 
https://github.com/RedHatInsights/insights-core/blob/cc2e26225b1db85eb11e3b160cb12b81d1b3796c/insights/parsers/ls_sys_firmware.py#L45-L46

2022-02-21 08:25 UTC, xiangce requested changes
@TZ3070 - Please check my new comments above

And 1) since this is a new parser file, please add doc entry for it in the `docs/shared_parsers_catalog/` dir, so that its online document can be generated automatically. 2), for newly added specs parsers, please raise an MR to the insights-core-assets repo at first to make sure they can be added to the uploader.json.

2022-02-21 08:25 UTC, xiangce commented on insights/parsers/ls_systemd.py
> +SystemdPerms - command ``/bin/ls -lanRL /etc/systemd``
This should be modified too.

2022-02-21 08:25 UTC, xiangce commented on insights/parsers/ls_systemd.py
> +UsrLibSystemdPerms - command ``/bin/ls -lanRL /usr/lib/systemd``
The same comment as above

2022-02-21 08:25 UTC, xiangce commented on insights/parsers/ls_systemd.py
> +class LsEtcSystemdPermsParser(CommandParser, FileListing):
How above remove the part of `PermsParser`?

2022-02-21 08:25 UTC, xiangce commented on insights/parsers/ls_systemd.py
> +class LsUsrLibSystemdPermsParser(CommandParser, FileListing):
How above remove the part of `PermsParser`?

2022-02-21 08:28 UTC, xiangce commented on insights/specs/default.py
> +    ls_etc_systemd = simple_command("/bin/ls -lanRL /etc/systemd")
You also need to add the `simple_command` spec to the `insights_archive.py` as a `simple_file` to make sure the `core` could find it from the insights-archive successfully. 

Please use the `mangle` command provide by the insights-core to get the `simple_file` of this `simple_command`

2022-02-21 08:28 UTC, xiangce commented on insights/specs/default.py
> +    ls_usr_lib_systemd = simple_command("/bin/ls -lanRL /usr/lib/systemd")
Same as above

2022-02-23 01:12 UTC, xiangce approved these changes

2022-02-23 04:30 UTC, xiangce approved these changes
Approved pending the approval of Specs.

2022-03-04 08:37 UTC, merged