Feat: Add teamdctl_config_dump spec to insights_archive
RedHatInsights/insights-core pull request #3472
Opened 2022-07-19 02:13 UTC by TZ3070

Signed-off-by: Xinting Li <xintli@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Add teamdctl_config_dump spec to default.py.

2022-07-21 03:14 UTC, xiangce requested changes
@TZ3070 - as the `teamctl_state_dump` please raise an issue to the core-assets repo for this spec change.

2022-07-21 06:15 UTC, psachin commented
I believe it is ` teamdctl_config_dump`.

2022-07-22 09:59 UTC, TZ3070 commented
> @TZ3070 - like the `teamctl_state_dump` please raise an issue to the core-assets repo for this spec change.

The issue has raised

2022-07-28 02:14 UTC, xiangce approved these changes

2022-07-28 02:14 UTC, merged