New Parser for container_installed_rpms
RedHatInsights/insights-core pull request #3560
Opened 2022-10-19 08:03 UTC by TZ3070

Signed-off-by: Xinting Li <xintli@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

New parser for installed rpm of container

2022-10-19 10:07 UTC, TZ3070 commented
The PR will continue after the 'container_execute' function is updated.

2022-10-25 08:34 UTC, xiangce requested changes

2022-10-25 08:34 UTC, xiangce commented on insights/parsers/installed_rpms.py
> +    """
Please add a `pass` for the empty class that fully inherits from the super.

2022-10-25 08:34 UTC, xiangce commented on insights/tests/parsers/test_installed_rpms.py
> +    assert rpm.epoch == '0'
Better add `Container` related items to the test. e.g. the `.engine`, `.image`, and `.container_id`, etc.

2022-10-26 03:24 UTC, xiangce approved these changes

2022-10-26 03:25 UTC, merged