fix: check list range to avoid exception
RedHatInsights/insights-core pull request #3576
Opened 2022-11-01 08:58 UTC by takayuki-nagata

Signed-off-by: Takayuki Nagata <tnagata@redhat.com>

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

`pcs config` shows empty `Corosync Nodes` on pacemaker remote nodes, and `data[in_line]` has an empty list. This fix checks the range before accessing `data[in_line][0]`. Without this fix, an exception is raised.

2022-11-01 18:00 UTC, ryan-blakley requested changes

2022-11-02 03:24 UTC, takayuki-nagata commented on insights/parsers/pcs_config.py
> +                if self.data[in_line]:
@ryan-blakley thank you for your review. I have resent new commit.

2022-11-02 13:04 UTC, ryan-blakley approved these changes
Looks good to me.

2022-11-03 01:02 UTC, xiangce approved these changes

2022-11-03 05:48 UTC, merged