Feat: New Parser for 'dotnet --version' Command
RedHatInsights/insights-core pull request #3581
Opened 2022-11-04 08:10 UTC by TZ3070

Signed-off-by: Xinting Li <xintli@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

New parser for dotnet --version in container

2022-11-08 01:35 UTC, xiangce requested changes
And please update the git commit msg more relevant.

2022-11-08 01:35 UTC, xiangce commented on insights/parsers/dotnet.py
> +class ContainerInstalledRpms(ContainerParser, DotNetVersion):
ContainerDotNetVersion

2022-11-08 07:58 UTC, xiangce approved these changes
Approved pending the approval of the Spec

2022-11-09 08:47 UTC, psachin approved these changes

2022-11-09 09:59 UTC, merged