[insights-core-3.0.300] Remove deprecated features
RedHatInsights/insights-core pull request #3595
Opened 2022-11-16 11:34 UTC by psachin

Signed-off-by: Sachin Patil <psachin@redhat.com>

### All Pull Requests:

Check all that apply:

* [X] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This PR will remove the deprecated features which are planned to remove after insights-core-3.0.300.

*Add your description here*

2022-11-16 18:33 UTC, ryan-blakley requested changes

2022-11-21 08:18 UTC, xiangce reviewed
@psachin - Per the discussion on the sync meeting, we suggested removing the RegisterPoints of the specs from `insights.specs.Specs` and their mapping in the relevant `insights.specs.DefaultSpecs` modules,  since after removing the parsers, these specs are not used elsewhere.

2022-11-21 08:18 UTC, xiangce commented on insights/combiners/modinfo.py
> +        for item in filter(None, []):
Better remove this whole `for` loop?

2022-11-22 04:14 UTC, psachin commented on insights/combiners/modinfo.py
> +        for item in filter(None, []):
Sure

2022-11-22 04:24 UTC, psachin commented on insights/combiners/modinfo.py
> -            "3.1.25"
Thanks for pointing that out. As this depends on `ModInfoAll` & `ModInfoEach` parser, I might have to delay to removal of these parsers after 3.1.25 if that seems ok to you.

2022-11-22 11:33 UTC, psachin commented
> @psachin - Per the discussion on the sync meeting, we suggested removing the RegisterPoints of the specs from `insights.specs.Specs` and their mapping in the relevant `insights.specs.DefaultSpecs/InsightsArchiveSpecs/SosSpecs` modules, since after removing the parsers, these specs are not used elsewhere.

Done

2022-11-28 13:57 UTC, ryan-blakley commented on insights/combiners/modinfo.py
> -            "3.1.25"
That's fine with me, whatever works best for you I'm good with.

2022-11-29 05:14 UTC, xiangce approved these changes

2022-11-29 06:41 UTC, xiangce commented
Hey All, since this PR has the high potential to break the running of the existing rules. I'd like to merge it in advance before the release day, to leave ample reaction time for us whenever any breakage happens.

2022-11-29 06:45 UTC, merged