Add container spec sys_cpu_online
RedHatInsights/insights-core pull request #3612
Opened 2022-11-25 13:26 UTC by wushiqinlou

Signed-off-by: jiazhang <jiazhang@redhat.com>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:
This spec is used to add container check on one insights-plugins advisor rule

2022-11-29 05:09 UTC, xiangce requested changes
This one seems to be duplicated with #3611, which one do you prefer to keep? And please get the spec approval at first.

2022-12-01 05:26 UTC, wushiqinlou commented
@xiangce - Please review.

2022-12-05 08:48 UTC, xiangce commented on insights/parsers/cpu_online.py
> +=======================================================
Please modify the length of this line?

2022-12-05 09:35 UTC, wushiqinlou commented on insights/parsers/cpu_online.py
> +=======================================================
@xiangce - Updated, please check

2022-12-07 06:17 UTC, xiangce approved these changes

2022-12-07 08:08 UTC, merged