[Enhancement] enhancing parser according to the requirement
RedHatInsights/insights-core pull request #3620
Opened 2022-12-01 20:04 UTC by mohitkumarrh

Signed-off-by: Mohit Kumar <mohikuma@REDHAT.COM>

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Needed to check the file inside `/var/lib/pcp/pmdas/openmetrics/config.d` Dir, insited of `/var/lib/pcp`. *

2022-12-02 04:33 UTC, mohitkumarrh commented
@xiangce please review

2022-12-02 08:25 UTC, xiangce commented
@mohitkumarrh - This is a kind of `SPEC Change` please open an MR for it to the core-assets repo to get it approved there first.

2022-12-09 07:30 UTC, mohitkumarrh commented
@xiangce - I have created the MR for it to the core-assets repo - https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/merge_requests/494 , Please Review

2022-12-14 06:09 UTC, xiangce requested changes

2022-12-14 06:09 UTC, xiangce commented on insights/parsers/ls_var_lib_pcp.py
>  =============================================
length...

2022-12-14 06:09 UTC, xiangce commented on insights/parsers/ls_var_lib_pcp.py
>  class LsVarLibPcp(CommandParser, FileListing):
Will this class name be modified accordingly?

2022-12-14 06:09 UTC, xiangce commented on insights/specs/default.py
> -    ls_var_lib_rsyslog = simple_command("/bin/ls -lZ /var/lib/rsyslog")
You shouldn't remove this spec.

2022-12-14 06:09 UTC, xiangce commented on insights/specs/insights_archive.py
> -    ls_var_lib_rsyslog = simple_file("insights_commands/ls_-lZ_.var.lib.rsyslog")
Please do not remove this spec.

2022-12-14 06:09 UTC, xiangce commented on insights/tests/parsers/test_ls_var_lib_pcp.py
> +    assert failed == 2
`failed == 2` means there are two test errors in the doc test, please fix them and ensure:
```assert failed == 0```

2022-12-15 05:33 UTC, mohitkumarrh commented
py.test:
```
______________________________________________________________________________ test_ls_var_lib_pcp _______________________________________________________________________________

    def test_ls_var_lib_pcp():
        ls_var_lib_pcp = LsVarLibPcpOpenmetricsConfigd(context_wrap(LS_VAR_LIB_PCP, path="insights_commands/ls_-la_.var.lib.pcp.pmdas.openmetrics.config.d"))
>       assert ls_var_lib_pcp.dirs_of('/var/lib/pcp/pmdas/openmetrics/config.d') == ['.', '..', 'grafana.url']

insights/tests/parsers/test_ls_var_lib_pcp.py:17: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <insights.parsers.ls_var_lib_pcp.LsVarLibPcpOpenmetricsConfigd object at 0x7fd618e42550>, directory = '/var/lib/pcp/pmdas/openmetrics/config.d'

    def dirs_of(self, directory):
        """
        The list of subdirectories in the given directory.
        """
>       return self.listings[directory]['dirs']
E       KeyError: '/var/lib/pcp/pmdas/openmetrics/config.d'

insights/core/__init__.py:1753: KeyError

---------- coverage: platform darwin, python 3.6.5-final-0 -----------
Name                                 Stmts   Miss Branch BrPart  Cover   Missing
--------------------------------------------------------------------------------
insights/parsers/ls_var_lib_pcp.py       6      0      2      0   100%
--------------------------------------------------------------------------------
TOTAL                                    6      0      2      0   100%

============================================================================ short test summary info =============================================================================

```

@xiangce i'm getting  KeyError: '/var/lib/pcp/pmdas/openmetrics/config.d' error, can you help me resolve it.

2022-12-16 09:35 UTC, xiangce commented
Hey @mohitkumarrh - I think this is a bug in the cooperation between the insights core vs the base module `ls_parser`, the insights core used the following `mangle` logic and replaced all of the `/` to `.` as the filename in the insights-archive:
https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/util/mangle.py#L40
But it didn't record which `.` is a `mangled` dot from the slash.

However, the `ls_parser` module converted all the `.` back to the `/` and didn't consider whether it's an original `.` in the `file_path`.

So the path `/var/lib/pcp/pmdas/openmetrics/config.d` in the parser result was stored as `/var/lib/pcp/pmdas/openmetrics/config/d` by mistake.

Since recently, we met a couple of issues in the `ls_parser`, I'm planning to do some enhancement on it. 
Could you please wait for a while?

Sorry about the inconvenience.

2022-12-19 04:23 UTC, mohitkumarrh commented
> Hey @mohitkumarrh - I think this is a bug in the cooperation between the insights core vs the base module `ls_parser`, the insights core used the following `mangle` logic and replaced all of the `/` to `.` as the filename in the insights-archive:
> 
> https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/util/mangle.py#L40
> 
> 
> But it didn't record which `.` is a `mangled` dot from the slash.
> However, the `FileListing` converted all the `.` back to the `/` and didn't consider whether it's an original `.` in the `file_path`:
> 
> https://github.com/RedHatInsights/insights-core/blob/8656cccc1cbe78e208ac5d1336503b33d447ef99/insights/core/__init__.py#L1722
> 
> So the path `/var/lib/pcp/pmdas/openmetrics/config.d` in the parser result was stored as `/var/lib/pcp/pmdas/openmetrics/config/d` by mistake.
> 
> Since recently, we met a couple of issues in the `ls_parser`, I'm planning to do some enhancement on it. Could you please wait for a while?
> 
> Sorry about the inconvenience.

@xiangce - I understand the issue i was facing due to this bug, I'll wait for the enhancement to be done to resolve this bug and change the MR accordingly.

2023-01-09 06:45 UTC, closed without merging