feat: New spec to get the duplicate machine id
RedHatInsights/insights-core pull request #3697
Opened 2023-03-07 07:15 UTC by huali027

feat: New spec to get the duplicate machine id and parser
### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

2023-03-07 07:19 UTC, huali027 commented
@xiangce Please help to review, thanks.

2023-03-07 08:58 UTC, xiangce requested changes
Besides of the following comments, you also need to add the `insights.specs.default.DefaultSpecs.machine_id` to the default manifest defined in the `collect.py`

2023-03-07 09:03 UTC, huali027 commented on insights/specs/datasources/machine_ids.py
> +        machine_id = str(machine_id_obj.content[0].strip())
When I test, it's a unicode, so I transfer it here.

2023-03-08 01:00 UTC, huali027 commented
@xiangce the code is updated based on comments and also returns the hostnames with the new requirement. Please help to review again, thanks.

2023-03-08 02:39 UTC, xiangce approved these changes

2023-03-08 02:41 UTC, merged