feat: logrotate client implementation
RedHatInsights/insights-core pull request #3702
Opened 2023-03-10 17:24 UTC by DuckBoss

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

This patch updates the logging file handler to no longer use a `RotatingFileHandler`
to prepare for the logrotate feature implementation in insights-client.
**Associated insights-client changes:** [insights-client PR](https://gitlab.cee.redhat.com/insights-platform/insights-client/-/merge_requests/49)

2023-03-14 15:49 UTC, ahitacat requested changes
The egg needs to still working in older versions of insights-client. Instead of removing we should change the log behavior  depending on the insights-client version.

2023-03-15 16:39 UTC, ahitacat approved these changes
This looks good to me

2023-03-21 06:44 UTC, xiangce commented
@DuckBoss - before merging this PR, could you please fix the failed test of python26?

```
    def test_get_log_handler_by_client_version(get_version_info, mock_path_dirname):
        '''
        Verify that get_log_handler() returns
        the correct file handler depending on
        the client rpm version.
        '''
        mock_path_dirname.return_value = "mock_dirname"
    
        # RPM version is older than 3.1.8
        get_version_info.return_value = {'client_version': '3.1.0'}
        conf = InsightsConfig(logging_file='/tmp/insights.log')
>       assert type(get_file_handler(conf)) is logging.handlers.RotatingFileHandler
E       AssertionError

insights/tests/client/test_client.py:133: AssertionError
```

2023-04-20 05:56 UTC, xiangce commented
The py26 test of this PR on my local is PASSED. I believe this is ready for release.

2023-04-20 05:56 UTC, merged