FEAT: Add new parser XFSQuotaStatue
RedHatInsights/insights-core pull request #3850
Opened 2023-07-12 06:05 UTC by TZ3070

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Add new parser XFSQuotaStatue for adviser rule

2023-07-12 09:43 UTC, xiangce requested changes

2023-07-12 09:43 UTC, xiangce commented on insights/parsers/xfs_quota.py
> +        for line in get_active_lines(content):
As currently, performance is considered in high priority, it's not recommended to use the `get_active_lines` against `content`, especially if it's got from a command (it's assumed that there are no comment lines, e.g. `# xxx`. Better skip the empty lines in the following loop by hand, e.g. `if not line.strip(); continue`

2023-07-12 09:43 UTC, xiangce commented on insights/parsers/xfs_quota.py
> +class XFSQuotaStatue(Parser):
CommandParser?

2023-07-12 09:43 UTC, xiangce commented on insights/specs/default.py
> +    xfs_quota_statue = simple_command("/sbin/xfs_quota -x -c 'state -gu'")
You also need to add its `simple_file` to the `insights_archive.py` if it also can be collected via uploader.json

2023-07-12 09:43 UTC, xiangce commented on insights/parsers/xfs_quota.py
> +XFSQuotaStatue - command ``/sbin/xfs_quota -x -c 'state -gu'``
`XFSQuotaState`?

2023-07-12 13:08 UTC, TZ3070 commented on insights/parsers/xfs_quota.py
> +XFSQuotaStatue - command ``/sbin/xfs_quota -x -c 'state -gu'``
@xiangce Updated, please review again

2023-07-13 05:17 UTC, xiangce approved these changes

2023-07-13 05:44 UTC, merged