wip: fix: yum unexpected ParseException
RedHatInsights/insights-core pull request #3855
Opened 2023-07-17 11:37 UTC by JoySnow

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [x] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Fix https://github.com/RedHatInsights/insights-core/issues/3854

2023-09-22 08:25 UTC, JoySnow commented
Hi @xiangce , could you help review the changes?

2023-10-09 01:26 UTC, xiangce approved these changes

2023-10-09 02:19 UTC, xiangce requested changes
@JoySnow - please fix the failed tests in py2 first.

2023-10-10 13:12 UTC, JoySnow commented
@xiangce , updated the code with a more compatible table handling way,  could you help review the code?

2023-10-18 09:07 UTC, xiangce approved these changes

2023-10-18 09:20 UTC, merged