Add parser intersystems_configuration_log
RedHatInsights/insights-core pull request #3861
Opened 2023-07-26 10:13 UTC by wushiqinlou

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

2023-08-02 07:46 UTC, xiangce requested changes

2023-08-02 07:46 UTC, xiangce commented on insights/specs/datasources/intersystems_iris.py
> +                                break
This is nitpicking but seems can simplify the code (reduced `for`)
```
filtered_content.append(line) if any(_f in line for _f in filters) else None
```

2023-08-02 07:46 UTC, xiangce commented on insights/specs/datasources/intersystems_iris.py
Just a question, would it be good that rename the datasource as `intersystems`, in case we have more sub-modules to add for specs relate to `intersystems`?

2023-08-02 07:46 UTC, xiangce commented on insights/specs/default.py
> +        sys_fs_cgroup_memory, sys_fs_cgroup_memory_tasks_number, intersystems_iris,
Please insert the new module into the list per the alpha order.

2023-08-02 07:46 UTC, xiangce commented on insights/specs/default.py
> +    intersystems_iris_messages_log = intersystems_iris.iris_working_messages_log
Is it okay to rename these specs as `iris_*` ?

2023-08-02 07:46 UTC, xiangce commented on insights/tests/parsers/test_iris.py
> +""".strip()
Since most of the content of this case is not used in the following test, better keep the required lines as less as we can.

2023-08-02 07:46 UTC, xiangce commented on insights/parsers/iris.py
> +from insights import LogFileOutput, parser
The `LogFileOutput` can be added to L8 too, and let's keep this line as it was.

The reason for this is to keep the alpha order the importing.

2023-08-02 07:46 UTC, xiangce commented on insights/specs/__init__.py
> +    intersystems_iris_messages_log = RegistryPoint(filterable=True)
Seems to need to move the two specs to after the `interrupts`. Or rename them as `iris_*`?

2023-08-02 07:46 UTC, xiangce commented on insights/parsers/iris.py
More parsers are added to this module, better update the title and add them to the docstring titles like,

```
Iris - InterSystems
======================
Parsers included in this module are:

IrisList - Command ``/usr/bin/iris list``
=========================================

IrisCpf - File ``iris.cpf``
=========================================

IrisMessages - File ``iris/messages.log``
=========================================



```

2023-08-02 07:46 UTC, xiangce commented on insights/specs/datasources/intersystems_iris.py
It needs to add the docstring compiling entry for this datasource as well. see the `docs/custom_datasources_index.rst`

2023-08-02 08:59 UTC, wushiqinlou commented
@xiangce - Updated according to your comments, please confirm

2023-08-03 01:11 UTC, xiangce commented on insights/collect.py
> +    # needed by the 'intersystems_iris_cpf' spec
you forget to update this spec name.

2023-08-03 01:11 UTC, xiangce commented on insights/collect.py
> +    # needed by the 'intersystems_iris_messages_log' spec
The same comment as above

2023-08-03 01:11 UTC, xiangce commented on insights/parsers/iris.py
> +======================
Better adjust the length of this underline

2023-08-03 01:11 UTC, xiangce commented on insights/parsers/iris.py
> +=========================================
The same comment as above

2023-08-03 01:11 UTC, xiangce commented on insights/parsers/iris.py
> +=========================================
The same comment as above

2023-08-03 01:48 UTC, xiangce approved these changes

2023-08-03 04:21 UTC, merged