Feat: Add new parser PostfixMaster
RedHatInsights/insights-core pull request #3898
Opened 2023-08-30 09:12 UTC by TZ3070

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Add new parser postfix_conf for adviser rule

2023-09-04 06:47 UTC, xiangce requested changes

2023-09-04 06:47 UTC, xiangce commented on insights/parsers/postfix_conf.py
> +        self.data = []
`.data` is not suggested to use.

2023-09-04 06:47 UTC, xiangce commented on insights/parsers/postfix_conf.py
> +class PostfixMaster(ConfigParser):
I'm wondering why `ConfigParser` is used for this parser, as I didn't check that the `parser_doc` is implemented and the super `parser_conent` is called.

2023-09-04 06:47 UTC, xiangce commented on insights/parsers/postfix_conf.py
> +PostfixMaster - file ``/etc/postfix/master.cf``
Please double confirm the title and the name of the python file. Did you use different names on purpose?

2023-09-04 09:10 UTC, TZ3070 commented on insights/parsers/postfix_conf.py
> +        self.data = []
Updated

2023-09-05 02:13 UTC, xiangce approved these changes

2023-09-05 02:14 UTC, merged