fix: check status created a machine-id file
RedHatInsights/insights-core pull request #3965
Opened 2023-12-04 18:25 UTC by ahitacat

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

When insights-client checked the status created a machine-id file to make some calls to the console service. That created a residual machine file if it had not access to the service (i.e. system was not registered to rhsm).

This PR refactors a bit the logic of generate_machine_id, and splits in a new function that will only get the machine id `get_machineid()`.

Checking status and `generate_machine_id` will use this new function.

Test have been changed and a new one has been created.

Resolves: CCT-161

2023-12-19 09:02 UTC, m-horky requested changes
This would solve it, but I am not really a fan of some of the parts.

1. Have you considered changing the original `client.get_machine_id` to accept a `create` flag, instead of creating a new function with similar name in the utils?
https://github.com/RedHatInsights/insights-core/blob/f5479075d961d45cea25638cb001cb83aa073da3/insights/client/client.py#L307-L308
2. If that would be too complicated, I found out you are only checking if the returned value is not None. Would it make sense to rename it to something like `machine_id_exists()` returning a bool?

2023-12-19 10:53 UTC, ahitacat commented
> 1. Have you considered changing the original `client.get_machine_id` to accept a `create` flag, instead of creating a new function with similar name in the utils?
>    https://github.com/RedHatInsights/insights-core/blob/f5479075d961d45cea25638cb001cb83aa073da3/insights/client/client.py#L307-L308

I considered that, but there is also a flag to create a new file, independently if it already exists. After this fix, I was considering to create a new ticket to make some effort refactoring this utility because is a bit entangled. Ideally, discerning the functions that use this method into 2, the ones that need by any cost an id, and the ones that doesn't need an id.


> 2. If that would be too complicated, I found out you are only checking if the returned value is not None. Would it make sense to rename it to something like `machine_id_exists()` returning a bool?
Not only, if it exists it returns the value of machine-id

2023-12-19 15:31 UTC, ahitacat commented
# Changelog

- Created a method to check if the machine-id file exists, this modify back the change on generate_machine_id function.
- Function that checked registration will check first if the machine-id file exists, it will avoid to generate a machine-id file if it don't exists. Solving the issue described in CCT-161

2023-12-19 15:38 UTC, m-horky requested changes

2023-12-19 15:38 UTC, m-horky commented on insights/tests/client/connection/test_LEGACY_reg_check.py
> +@patch("insights.client.connection.False", return_value=True)
This is probably a bad copy-paste

2023-12-20 16:18 UTC, m-horky approved these changes
LGTM

2024-01-26 09:28 UTC, ahitacat commented
test me

2024-01-30 09:04 UTC, zhangqianqian commented
Verification pass on this open PR, please refer details: https://issues.redhat.com/browse/CCT-161

2024-01-30 10:56 UTC, ahitacat commented
@xiangce This can be on the next egg release

2024-02-06 11:45 UTC, merged