feat: Add "systemd" to the spec "rpm -V"
RedHatInsights/insights-core pull request #3990
Opened 2024-01-09 02:12 UTC by huali027

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

2024-01-09 02:15 UTC, huali027 commented
@xiangce @JoySnow Please help to review, thanks.

2024-01-09 07:02 UTC, JoySnow approved these changes

2024-01-11 01:11 UTC, xiangce requested changes
1. For this spec Change, please get it approved in the asset repo. 
2. Its spec in the `insights_archive.py` should also be updated, BTW, please use `first_file` to compatible the old list.
3. And the corresponding symbolic in `uploader.json` should also be updated

2024-01-11 01:42 UTC, huali027 commented
> 1. For this spec Change, please get it approved in the asset repo.
> 2. Its spec in the `insights_archive.py` should also be updated, BTW, please use `first_file` to compatible the old list.
> 3. And the corresponding symbolic in `uploader.json` should also be updated

Thanks for the remind, I updated it now, please have a review again.

2024-01-11 02:37 UTC, xiangce approved these changes

2024-01-11 05:11 UTC, merged