feat: New spec "rhui-set-release" and parser
RedHatInsights/insights-core pull request #3998
Opened 2024-01-25 08:55 UTC by huali027

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

2024-01-25 08:59 UTC, huali027 commented
@xiangce @JoySnow Please help to review, thanks.

2024-01-29 04:12 UTC, JoySnow requested changes
Hi @huali027 , I am good with the changes.  Just missing a tiny update of docstings:

2024-01-29 04:18 UTC, JoySnow commented
About this parser `SubscriptionManagerReleaseShow`, its spec `Specs.subscription_manager_release_show` was no more collected. ( https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/commit/5a1e057bac0d402b290eb17a6100ca61f78b1370 )  

Thinking about deleting the including of parser `SubscriptionManagerReleaseShow` in it's combiner. 

Well, found that this `Specs.subscription_manager_release_show` is still widely used in Advisor rules' test files. 

Okay, we should keep including this `SubscriptionManagerReleaseShow` here at least for now. 

---- 

BTW, should we consider to mark `deprecation` of parser `SubscriptionManagerReleaseShow` ?  @xiangce

2024-01-31 03:19 UTC, xiangce commented
> About this parser `SubscriptionManagerReleaseShow`, its spec `Specs.subscription_manager_release_show` was no more collected. ( https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/commit/5a1e057bac0d402b290eb17a6100ca61f78b1370 )
> 
> Thinking about deleting the including of parser `SubscriptionManagerReleaseShow` in it's combiner.
> 
> Well, found that this `Specs.subscription_manager_release_show` is still widely used in Advisor rules' test files.
> 
> Okay, we should keep including this `SubscriptionManagerReleaseShow` here at least for now.
> 
> BTW, should we consider to mark `deprecation` of parser `SubscriptionManagerReleaseShow` ? @xiangce

@JoySnow - Yeap, let's deprecate it and update the rules accordingly

2024-01-31 07:10 UTC, JoySnow commented
Opened a new thread - [RHINENG-7882](https://issues.redhat.com/browse/RHINENG-7882) to track the parser deprecation. @xiangce 

> > About this parser `SubscriptionManagerReleaseShow`, its spec `Specs.subscription_manager_release_show` was no more collected. ( https://gitlab.cee.redhat.com/insights-release-eng/insights-core-assets/-/commit/5a1e057bac0d402b290eb17a6100ca61f78b1370 )
> > Thinking about deleting the including of parser `SubscriptionManagerReleaseShow` in it's combiner.
> > Well, found that this `Specs.subscription_manager_release_show` is still widely used in Advisor rules' test files.
> > Okay, we should keep including this `SubscriptionManagerReleaseShow` here at least for now.
> > BTW, should we consider to mark `deprecation` of parser `SubscriptionManagerReleaseShow` ? @xiangce
> 
> @JoySnow - Yeap, let's deprecate it and update the rules accordingly

2024-02-01 05:23 UTC, JoySnow approved these changes

2024-02-01 05:41 UTC, xiangce commented
@huali027 - please fix the conflicts

2024-02-01 05:56 UTC, xiangce commented on insights/specs/__init__.py
> +    rhui_set_release = RegistryPoint()
Per the spec application MR in the assets repo, this spec should be marked as `no_obfuscate=['hostname', 'ip']`

2024-02-01 06:56 UTC, xiangce approved these changes

2024-02-01 07:37 UTC, merged