Add miss dependency specs
RedHatInsights/insights-core pull request #4020
Opened 2024-02-13 03:04 UTC by wushiqinlou

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

* Add back the specs removed by mistake in https://github.com/RedHatInsights/insights-core/pull/2663/files
* Remove "lvs_headings, pvs_headings, vgs_headings"

2024-02-13 05:30 UTC, xiangce requested changes
@wushiqinlou - generally, before removing existing parsers, we'd mark them as `deprecated` first. And we'd better split the adding specs and removing specs/parsers into separate PRs.

2024-02-16 02:11 UTC, wushiqinlou commented
@xiangce - `deprecated` the existing parsers in https://github.com/RedHatInsights/insights-core/pull/4025, please confirm

2024-02-27 07:40 UTC, xiangce commented on insights/specs/datasources/dumpdev.py
Sorry for replying late, as we have an exiting python module named `mount` in the `insights/specs/datasources` dir, would you mind moving this new `dumpdev_list` to the existing one? 
Or, it's required to add one more doc entry to the `docs/custom_datasources_index.rst` file.

2024-02-28 09:01 UTC, wushiqinlou commented
@xiangce - please check

2024-02-28 09:04 UTC, xiangce approved these changes

2024-02-28 09:05 UTC, merged