fix: insights-client failed, when --group was used
RedHatInsights/insights-core pull request #4070
Opened 2024-04-03 16:50 UTC by jirihnidek

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

* Card ID: CCT-186
* When system was registered against Satellite server, and "insights-client --register" was triggered --group="tag" CLI option, then registration failed
* Satellite also contains some bug, and it always returns status code 200 and empty list regardless existence of given group.

2024-04-04 10:57 UTC, xiangce commented
FYI, please don't worry about the failure of CI/CD, it was not caused by this PR and will be fixed once the new `uploader.json` is released. Please ignore it for now.

2024-04-05 08:07 UTC, jirihnidek commented
I can see that Jenkins jobs failed, but I cannot see, why did it fail.

2024-04-07 01:11 UTC, xiangce commented
> I can see that Jenkins jobs failed, but I cannot see, why did it fail.
Please ignore it too. It's a known issue mentioned in CCT-435. The QE team will fix it soon. Please ignore the other failures as well and start the review processes.

2024-05-14 09:21 UTC, m-horky requested changes
It's a shame we had to inflate the function by this much. It doesn't seem to be breaking anything by accident, and while it all looks ugly, there may be no way to save it.

Can you please revert the formatting changes that are committed with this change on other parts of the file?

2024-05-14 09:21 UTC, m-horky commented on insights/client/connection.py
> +                    api_group_id = results
You seem to be overwriting the value you have set one line above.

2024-06-03 12:53 UTC, m-horky reviewed
Would it be possible to create tests for this? Mock out some example responses the server can return. To be honest, I'm kind of lost in this method now, I'd like to see the difference between hosted and Satellite.

2024-06-10 14:56 UTC, jirihnidek commented
> Would it be possible to create tests for this? Mock out some example responses the server can return. To be honest, I'm kind of lost in this method now, I'd like to see the difference between hosted and Satellite.

I will try to do that.

2024-06-24 16:04 UTC, m-horky requested changes
Thank you. Would it be possible to add a test for the Satellite case as well? I'd like to have it covered as well. Just one more test that would show that response code 200 may not be enough.

2024-07-01 07:56 UTC, jirihnidek commented
> Thank you. Would it be possible to add a test for the Satellite case as well? I'd like to have it covered as well. Just one more test that would show that response code 200 may not be enough.

What exactly do you mean to add test for the Satellite case?

2024-07-01 08:12 UTC, m-horky commented
> Satellite also contains some bug, and it always returns status code 200 and empty list regardless existence of given group.

Something that would mock a response like that -- server returning 200 with empty list. The method in `connection.py` grew a lot, but the tests don't don't seem to be covering the edge case your patch was addressing.

2024-07-26 12:39 UTC, m-horky approved these changes
ACK

2024-08-02 01:54 UTC, xiangce commented
May I know if this Pr ready for merge?

2024-08-02 07:40 UTC, m-horky commented
@xiangce Hi, I believe we're waiting for QE to verify this patch. I'll ping you once it is ready.

2024-08-07 15:03 UTC, m-horky commented
@xiangce Ready to be merged :+1:

2024-08-08 01:07 UTC, merged