wqfix: debug print of egg versions doesn't handle corrupted eggs
RedHatInsights/insights-core pull request #4101
Opened 2024-05-10 13:43 UTC by grunwmar

New if-else statement is added to check if exit code of previous Popen call is == 0 . Statement is added to insights.client.utilities.print_egg_version method.

CARD ID: CCT-406

### All Pull Requests:

Check all that apply:

* [x] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [x] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Originally, when unimportable egg was encountered, Insights client logged part of the traceback to the DEBUG log. I added a functionality which checks exit code of corresponding subprocess calling import and egg and if the code is not == 0, then it results to message ""path/to/egg: Corrupted egg." I was not able to capture exception from subprocess, so I choose this approach by using exit status. There is space for discussion whether there could happen another scenarios other than unimportable corrupted egg. Non-existing egg is already handled in code before.

2024-05-13 09:38 UTC, m-horky requested changes

2024-05-13 10:24 UTC, grunwmar commented on insights/client/utilities.py
> +            logger.debug('%s: Corrupted egg.', egg)
@m-horky Thanks for feedback. Yes, that's why asked for discussion. I have changed the message to `%s: Could not read egg version` and logged `stdout` output. `stderr` is already redirected to `stdout` in `Popen` constructor.

2024-05-31 18:49 UTC, DuckBoss commented on insights/client/utilities.py
> +            logger.debug('%s: %s', egg, stdout)
Also, just minor nitpicking, can you also update the commit title and pr title to remove the `wq` from `wqfix:...`?
`vim` strikes again :smiley:

2024-06-04 14:49 UTC, DuckBoss approved these changes
LGTM, thanks! :+1: 

:warning: Please wait for re-base before merging :warning:

2024-06-13 17:51 UTC, DuckBoss commented
@xiangce this LGTM after recent rebase and my testing, can you merge this?

2024-06-14 00:41 UTC, merged

2024-07-02 08:36 UTC, Glutexo reviewed
We found an interesting 🐛 when the developer has the _insights-core_ package installed locally. This happens naturally, because the development [guide](https://insights-core-tutorials.readthedocs.io/en/latest/prep_tutorial_env.html#manual-setup-not-required-if-you-ran-setup-env-sh) tells us to run

```sh
$ pip install -e .[develop]
```

to install dependencies. The command, however, only installs the dependencies as a side-effect of installing the insights-core itself, putting in into PYTHONPATH. As a result, any subprocess spawned knows about the locally installed egg and falls back to it if a manually provided egg can’t be loaded.

```python
Popen([
    sys.executable,
    '-c',
    'from insights import package_info; print(\'%s-%s\' % (package_info[\'VERSION\'], package_info[\'RELEASE\']))'],
    env={'PYTHONPATH': egg, 'PATH': os.getenv('PATH')},
    stdout=PIPE,
    stderr=STDOUT
)
```

In this call, an egg is manually prepended to PYTHONPATH, forcing Python to (try to) load it first. If the egg is broken and can’t be imported, Python then imports the locally installed egg. The call is seemingly successful and

```python
logger.debug('%s: %s', egg, version)
```

prints then the version mislabeled.

2024-07-02 08:50 UTC, m-horky commented
@Glutexo Please report that as a Jira ticket if it needs solving, we don't monitor closed PRs.

2024-07-02 10:11 UTC, Glutexo commented
Yet, you noticed! 😎

2024-07-02 13:36 UTC, DuckBoss commented
Thanks for noticing this and providing detailed information! It looks like our QE team has caught this case as well (refer to the jira). Please create a card for this and ping/assign me on it :)