FEAT: Add new parser Env
RedHatInsights/insights-core pull request #4196
Opened 2024-08-21 04:17 UTC by TZ3070

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

Add new parser Env

2024-08-21 06:01 UTC, xiangce requested changes

2024-08-21 06:01 UTC, xiangce commented on insights/parsers/env.py
> +class Env(CommandParser, list):
Why not use `dict`?

2024-08-21 06:04 UTC, TZ3070 commented
@xiangce ACK
@JoySnow Please hold the review because the card may abandon.

2024-09-03 06:37 UTC, TZ3070 commented
Close the PR because the card is abandoned.

2024-09-03 06:37 UTC, closed without merging