parsers: add parser for image builder facts (RHINENG-13943)
RedHatInsights/insights-core pull request #4261
Opened 2024-10-28 14:27 UTC by croissanne

### All Pull Requests:

Check all that apply:

* [ ] Have you followed the guidelines in our Contributing document, including the instructions about commit messages?
* [ ] No Sensitive Data in this change?
* [ ] Is this PR to correct an issue?
* [ ] Is this PR an enhancement?

### Complete Description of Additions/Changes:

*Add your description here*

2024-10-30 08:50 UTC, JoySnow requested changes
Hey @croissanne , thanks for your contribution.  This new parser `ImageBuilderFacts` is all good functional.  Here are some minor change suggestions, please check them inline ...

2024-10-30 08:50 UTC, JoySnow commented on insights/parsers/image_builder_facts.py
> +=========================================================
For insights-core doc build, the length of this line shall be align to the line above.

2024-10-30 08:50 UTC, JoySnow commented on insights/parsers/image_builder_facts.py
> +from .. import JSONParser, parser
insights-core is promoting the absolute import nowadays, what about change to : 
```suggestion
from insights.core import JSONParser
from insights.core.plugins import parser
```

2024-10-30 08:50 UTC, JoySnow commented on insights/parsers/image_builder_facts.py
> +    pass
Seeing that you had a doc test `test_image_builder_facts_doc_examples`, could you add a corresponding docstrings test for this parser, an example could be : https://github.com/RedHatInsights/insights-core/blob/master/insights/parsers/bootc.py#L49-L53

2024-10-31 05:29 UTC, xiangce approved these changes

2024-10-31 05:30 UTC, merged